apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: rabbitmq02.haimacloud.com
 namespace: middleware
 annotations:
   kubernetes.io/ingress.class: traefik
spec:
 rules:
 - host: rabbitmq02.haimacloud.com
   http:
     paths:
     - backend:
         serviceName: rabbitmq-management02
         servicePort: 15672
